---
title: "Pensum"
output:
  pdf_document: default
  word_document: default
  html_document:
    df_print: paged
bibliography: references.bib
---

All books in the syllabus are available online, some also in print.

## Spatial Data Science[@bivand]

-   Chap. 1-5 Introduction
-   Chap. 7.1 - 7.2 sf
-   Chap. 8.1 `st_read` with query
-   Chap. 9 Plotting maps
-   Chap. 15 Spatial Regression

## **Geocomputation with R**[@muenchow]

-   Chap. 1 Introduction
-   Chap. 2.1, 2.2, 2.4 and 2.5 Geographic data in R
-   Chap. 3.1, 3.2 Attribute data operations
-   Chap. 4.1, 4.2 Spatial data operations
-   Chap. 5.1, 5.2 Geometry operations
-   Chap. 6.1 - 6.5 Reprojecting geographic data
-   Chap. 7 Geographic data I/O
-   Chap. 8.1, 8.2, 8.6

## Fundamentals of Data Visualization[@wilkeFundamentalsDataVisualization]

-   Chap. 12 Visualizing associations among two or more quantitative
    variables
-   Chap. 15 Visualizing geospatial data

## Data Visualization; A practical introduction[@healyDataVisualizationPractical2019]

-   Chap. 7 Draw maps

# Bibliography
